### ISSUE TITLE
Account saved but says not saved

### ISSUE THREAD

**Issue by OneSuperCad** [Nightkingale/Wii-U-Account-Swap#9]
So, I click "Backup the account.dat File" and it works, it says are you sure, then I hit A and it works, but then I hit "Swap to Pretendo Network ID" and it says "An exception has occurred! Have you made a backup for this user and account?" and it says to report it, so here I am.

**Comment by Nightkingale** [comment]
Hey, thanks for reporting! I'm not 100% sure yet if this is a bug since I'm not able to replicate the issue on my end, nor have I otherwise heard of this issue.

You'll need to do a few different steps to swap between Nintendo and Pretendo accounts, basically you'll end up backing up twice. Check out what I posted on issue #3 and see if maybe following those steps help you? You will only need to follow this setup process once, then in the future you will be able to swap between the two with the corresponding options.

Keep me posted if that helps, and if not, I can help you troubleshoot further.
